name: Electron-CI

# Launching the script on pushes or pull requests.
on: 
  push:
    branches: 
      - test
  pull_request:
    branches: 
      - test

jobs:
  test-and-build-app:
    runs-on: ubuntu-latest # TODO: Need to make it run on OSX and windows.
    steps:

      # Imports the source code to the ubuntu virtual machine
      - name: Getting the source code
        uses: actions/checkout@v2
        with:
          ref: 'test'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install project dependencies
        run: |
          yarn install

      - name: Transpile javascript files
        run: |
          yarn build

      - name: Run lint
        run: |
          yarn lint

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: |
            yarn test


      - name: Build the app
        run: |
          yarn make